namespace Odin.CodeAnnotations;

public enum ValidationStrategy
{
	UnifiedInDefault = 0,
	CreateUpdate,
	None,
}

public enum ValidationRuleSet
{
	Default = 0,
	Create,
	Update
}

public enum RequiredMode
{
	NotEmpty = 0,
	NotNull
}

[AttributeUsage(AttributeTargets.Class)]
public class AutoGeneratedValidationAttribute(
	ValidationStrategy validationStrategy = ValidationStrategy.UnifiedInDefault
) : Attribute
{
	public ValidationStrategy ValidationStrategy { get; } = validationStrategy;
}

/// <summary>
/// Sourcegen for validation.
/// </summary>
/// <param name="ignoreDataType"></param>
/// <param name="ignoreRequired"></param>
/// <param name="validationRuleSet"></param>
/// <param name="forceRequired">Forces required to be true, even when nullable.
/// Useful for enums/structs so they won't defaults but are required.
/// </param>
/// <param name="requiredMode">Determine the required mode.</param>
[AttributeUsage(AttributeTargets.Property)]
public class AutoGeneratedValidationPropAttribute(
	bool ignoreDataType = false,
	bool ignoreRequired = false,
	ValidationRuleSet validationRuleSet = ValidationRuleSet.Create,
	bool forceRequired = false,
	RequiredMode requiredMode = RequiredMode.NotEmpty
) : Attribute
{
	public bool IgnoreRequired { get; } = ignoreRequired;
	public bool ForceRequired { get; } = forceRequired;

	public bool IgnoreDataType { get; } = ignoreDataType;

	public ValidationRuleSet ValidationRuleSet { get; } = validationRuleSet;
	public RequiredMode RequiredMode { get; } = requiredMode;
}
