namespace Odin.CodeAnnotations;

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
public abstract class AutoGeneratedClassMappingAttribute : Attribute
{
	internal AutoGeneratedClassMappingAttribute(string boundToType, MappingBindingType bindingType, bool forceDeltaGen)
	{
		BindingType = bindingType;
		BoundToType = boundToType;
		ForceDeltaGen = forceDeltaGen;
	}

	public string BoundToType { get; }

	public MappingBindingType BindingType { get; }

	public bool ForceDeltaGen { get; }
}

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
public class AutoGeneratedClassMapToAttribute : AutoGeneratedClassMappingAttribute
{

	/// <summary>
	/// Auto generate mapping from this class to the specified type.
	/// </summary>
	/// <param name="mapToType"></param>
	/// <param name="forceDeltaGen">Determines whether to force generate Delta mapping and skip convention check e.g. 'Input' suffix</param>
	public AutoGeneratedClassMapToAttribute(Type mapToType, bool forceDeltaGen = false)
		: base(mapToType.FullName, MappingBindingType.To, forceDeltaGen)
	{
	}

	/// <summary>
	/// Auto generate mapping from this class to the specified type.
	/// </summary>
	/// <param name="mapToType"></param>
	/// <param name="forceDeltaGen">Determines whether to force generate Delta mapping and skip convention check e.g. 'Input' suffix</param>
	private AutoGeneratedClassMapToAttribute(string mapToType, bool forceDeltaGen = false)
		: base(mapToType, MappingBindingType.To, forceDeltaGen)
	{
	}
}

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
public class AutoGeneratedClassMapFromAttribute : AutoGeneratedClassMappingAttribute
{
	/// <summary>
	/// Auto generate mapping to this class from the specified type.
	/// </summary>
	/// <param name="mapFromType"></param>
	/// <param name="forceDeltaGen">Determines whether to force generate Delta mapping and skip convention check e.g. 'Input' suffix</param>
	public AutoGeneratedClassMapFromAttribute(Type mapFromType, bool forceDeltaGen = false)
		: base(mapFromType.FullName, MappingBindingType.From, forceDeltaGen)
	{
	}

	/// <summary>
	/// Auto generate mapping to this class from the specified type.
	/// </summary>
	/// <param name="mapFromType"></param>
	/// <param name="forceDeltaGen">Determines whether to force generate Delta mapping and skip convention check e.g. 'Input' suffix</param>
	private AutoGeneratedClassMapFromAttribute(string mapFromType, bool forceDeltaGen = false)
		: base(mapFromType, MappingBindingType.From, forceDeltaGen)
	{
	}
}

[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
public class AutoGeneratedClassMapIgnoreAttribute : Attribute
{
}
